const bibleVerse = function(){
  this.VERSES = [
    "Rejoice always, pray continually, give thanks in all circumstances; for this is God’s will for you in Christ Jesus. 1 Thessalonians 5:16-18",
    "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus. Philippians 4:6-7",
    "This is the confidence we have in approaching God: that if we ask anything according to his will, he hears us. 1 John 5:14",
    "Devote yourselves to prayer, being watchful and thankful. Colossians 4:2",
    "Therefore I tell you, whatever you ask for in prayer, believe that you have received it, and it will be yours. Mark 11:24",
    "Then you will call on me and come and pray to me, and I will listen to you. Jeremiah 29:12",
    "Be joyful in hope, patient in affliction, faithful in prayer. Romans 12:12",
    "The Lord is near to all who call on him, to all who call on him in truth. Psalm 145:18",
    "Call to me and I will answer you and tell you great and unsearchable things you do not know. Jeremiah 33:3",
    "About midnight Paul and Silas were praying and singing hymns to God, and the other prisoners were listening to them. Acts 16:25",
    "And when you pray, do not keep on babbling like pagans, for they think they will be heard because of their many words. Matthew 6:7",
    "Let us then approach God’s throne of grace with confidence, so that we may receive mercy and find grace to help us in our time of need. Hebrews 4:16",
    "For where two or three gather in my name, there am I with them. Matthew 18:20",
    "In my distress I called to the Lord; I cried to my God for help. From his temple he heard my voice; my cry came before him, into his ears. Psalm 18:6",
    "But when you pray, go into your room, close the door and pray to your Father, who is unseen. Then your Father, who sees what is done in secret, will reward you. Matthew 6:6",
    "And if we know that he hears us—whatever we ask—we know that we have what we asked of him. 1 John 5:15",
    "Therefore confess your sins to each other and pray for each other so that you may be healed. The prayer of a righteous person is powerful and effective. James 5:16",
    "But when you ask, you must believe and not doubt, because the one who doubts is like a wave of the sea, blown and tossed by the wind. James 1:6",
    "You did not choose me, but I chose you and appointed you so that you might go and bear fruit—fruit that will last—and so that whatever you ask in my name the Father will give you. John 15:16",
    "The end of all things is near. Therefore be alert and of sober mind so that you may pray. 1 Peter 4:7",
    "I cried out to him with my mouth; his praise was on my tongue. Psalm 66:17",
    "They all joined together constantly in prayer, along with the women and Mary the mother of Jesus, and with his brothers. Acts 1:14",
    "And I will do whatever you ask in my name, so that the Father may be glorified in the Son. John 14:13",
    "But to you who are listening I say: Love your enemies, do good to those who hate you, bless those who curse you, pray for those who mistreat you. Luke 6:27-28",
    "You desire but do not have, so you kill. You covet but you cannot get what you want, so you quarrel and fight. You do not have because you do not ask God. James 4:2",
    "If you believe, you will receive whatever you ask for in prayer. Matthew 21:22",
    "In the same way, the Spirit helps us in our weakness. We do not know what we ought to pray for, but the Spirit himself intercedes for us through wordless groans. Romans 8:26",
    "In the morning, Lord, you hear my voice; in the morning I lay my requests before you and wait expectantly. Psalm 5:3",
    "By day the Lord directs his love, at night his song is with me— a prayer to the God of my life. Psalm 42:8",
    "Dear friend, I pray that you may enjoy good health and that all may go well with you, even as your soul is getting along well. 3 John 1:2",
    "Lord, hear my prayer, listen to my cry for mercy; in your faithfulness and righteousness come to my relief. Psalm 143:1",
    "Watch and pray so that you will not fall into temptation. The spirit is willing, but the flesh is weak. Matthew 26:41",
    "When hard pressed, I cried to the Lord; he brought me into a spacious place. Psalm 118:5",
    "For I know that through your prayers and God’s provision of the Spirit of Jesus Christ what has happened to me will turn out for my deliverance. Philippians 1:19",
    "For the eyes of the Lord are on the righteous and his ears are attentive to their prayer, but the face of the Lord is against those who do evil. 1 Peter 3:12",
    "So we fasted and petitioned our God about this, and he answered our prayer. Ezra 8:23",
    "May these words of my mouth and this meditation of my heart be pleasing in your sight, Lord, my Rock and my Redeemer. Psalm 19:14",
    "This, then, is how you should pray: ‘Our Father in heaven, hallowed be your name, your kingdom come, your will be done, on earth as it is in heaven.’Matthew 6:9-10",
    "Is anyone among you sick? Let them call the elders of the church to pray over them and anoint them with oil in the name of the Lord. And the prayer offered in faith will make the sick person well; the Lord will raise them up. If they have sinned, they will be forgiven. James 5:14-15",
    "This poor man called, and the Lord heard him; he saved him out of all his troubles. Psalm 34:6",
    "If you then, though you are evil, know how to give good gifts to your children, how much more will your Father in heaven give the Holy Spirit to those who ask him! Luke 11:13",
    "And when you stand praying, if you hold anything against anyone, forgive them, so that your Father in heaven may forgive you your sins. Mark 11:25",
    "And everyone who calls on the name of the Lord will be saved. Acts 2:21",
    "So Peter was kept in prison, but the church was earnestly praying to God for him. Acts 12:5",
    "After Job had prayed for his friends, the Lord restored his fortunes and gave him twice as much as he had before. Job 42:10",
    "After they prayed, the place where they were meeting was shaken. And they were all filled with the Holy Spirit and spoke the word of God boldly. Acts 4:31",
    "Go back and tell Hezekiah, the ruler of my people, ‘This is what the Lord, the God of your father David, says: I have heard your prayer and seen your tears; I will heal you. On the third day from now you will go up to the temple of the Lord.’ 2 Kings 20:5",
    "But I tell you, love your enemies and pray for those who persecute you. Matthew 5:44",
    "I thank and praise you, God of my ancestors: You have given me wisdom and power, you have made known to me what we asked of you, you have made known to us the dream of the king. Daniel 2:23",
    "Father, I want those you have given me to be with me where I am, and to see my glory, the glory you have given me because you loved me before the creation of the world. John 17:24",
    "Arise, Lord! Lift up your hand, O God. Do not forget the helpless. Psalm 10:12",
    "I have made you known to them, and will continue to make you known in order that the love you have for me may be in them and that I myself may be in them. John 17:26",
    "So after they had fasted and prayed, they placed their hands on them and sent them off. Acts 13:3",
    "They devoted themselves to the apostles’ teaching and to fellowship, to the breaking of bread and to prayer. Acts 2:42",
    "Hear my prayer, Lord, listen to my cry for help; do not be deaf to my weeping. I dwell with you as a foreigner, a stranger, as all my ancestors were. Psalm 39:12",
    "And lead us not into temptation, but deliver us from the evil one. Matthew 6:13",
    "And forgive us our debts, as we also have forgiven our debtors. Matthew 6:12",
    "While they were worshiping the Lord and fasting, the Holy Spirit said, “Set apart for me Barnabas and Saul for the work to which I have called them.” Acts 13:2",
    "Taking the five loaves and the two fish and looking up to heaven, he gave thanks and broke them. Then he gave them to the disciples to distribute to the people. They all ate and were satisfied, and the disciples picked up twelve basketfuls of broken pieces that were left over. Luke 9:16-17",
    "Give us today our daily bread. Matthew 6:11",
    "Husbands, in the same way be considerate as you live with your wives, and treat them with respect as the weaker partner and as heirs with you of the gracious gift of life, so that nothing will hinder your prayers. 1 Peter 3:7",
    "I will strengthen Judah and save the tribes of Joseph. I will restore them because I have compassion on them. They will be as though I had not rejected them, for I am the Lord their God and I will answer them. Zechariah 10:6",
    "When all the people were being baptized, Jesus was baptized too. And as he was praying, heaven was opened and the Holy Spirit descended on him in bodily form like a dove. And a voice came from heaven: “You are my Son, whom I love; with you I am well pleased.” Luke 3:21-22",
    "And pray in the Spirit on all occasions with all kinds of prayers and requests. With this in mind, be alert and always keep on praying for all the Lord’s people. Ephesians 6:18",
    ]
}

module.exports = {bibleVerse};